"""candidate needs_info and flags

Revision ID: 24328c514c19
Revises: c47e4afe81df
Create Date: 2026-07-24 15:31:24.851749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24328c514c19'
down_revision: Union[str, Sequence[str], None] = 'c47e4afe81df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('flags', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('flags')
        batch_op.drop_column('needs_info')

    # ### end Alembic commands ###
