"""tenancy: companies, users, campaign scoping, candidate FK cascade

Revision ID: c47e4afe81df
Revises: 8b7c83e61dd8
Create Date: 2026-07-24 14:47:15.180865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47e4afe81df'
down_revision: Union[str, Sequence[str], None] = '8b7c83e61dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('region', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('requirements', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('token_usage', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_campaigns_company_id'), ['company_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_campaigns_company_id_companies'), 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_campaigns_created_by_users'), 'users', ['created_by'], ['id'])

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.alter_column('campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_candidates_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_candidates_campaign_id_campaigns'), 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_candidates_campaign_id_campaigns'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_candidates_campaign_id'))
        batch_op.alter_column('campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_campaigns_created_by_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_campaigns_company_id_companies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_campaigns_company_id'))
        batch_op.drop_column('finished_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('token_usage')
        batch_op.drop_column('requirements')
        batch_op.drop_column('region')
        batch_op.drop_column('created_by')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
